# Generated by Django 5.0.3 on 2024-03-29 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_school_programs_remove_school_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('school_website', models.URLField(null=True)),
                ('public_private', models.CharField(max_length=20, null=True)),
                ('school_representative', models.CharField(max_length=100, null=True)),
                ('school_rep_phone_num', models.CharField(max_length=20, null=True)),
                ('school_rep_email', models.EmailField(max_length=254, null=True)),
                ('school_logo', models.ImageField(null=True, upload_to='logos/')),
                ('school_image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='activities',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schools'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schools'),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schools'),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schools'),
        ),
        migrations.AlterField(
            model_name='featureshighlights',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schools'),
        ),
        migrations.AlterField(
            model_name='location',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schools'),
        ),
        migrations.AlterField(
            model_name='news',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schools'),
        ),
        migrations.AlterField(
            model_name='programsoffered',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schools'),
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
