# Generated by Django 5.0.3 on 2024-04-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_schools_alter_activities_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schools',
            name='school_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
