# Generated by Django 5.0.3 on 2024-04-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_schools_school_location_delete_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='school_image',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='schools',
            name='school_logo',
            field=models.ImageField(null=True, upload_to='media/logos/'),
        ),
    ]
