# Generated by Django 5.0.3 on 2024-04-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_schools_school_image_alter_schools_school_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='school_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='schools',
            name='school_logo',
            field=models.ImageField(null=True, upload_to='logos/'),
        ),
    ]
