# Generated by Django 5.0.3 on 2024-04-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_schools_school_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='public_private',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=20, null=True),
        ),
    ]
