# Generated by Django 5.0.3 on 2024-04-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_schools_public_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='activity_image',
            field=models.ImageField(null=True, upload_to='activities/'),
        ),
        migrations.AddField(
            model_name='clubs',
            name='club_image',
            field=models.ImageField(null=True, upload_to='clubs/'),
        ),
        migrations.AddField(
            model_name='facilities',
            name='facility_image',
            field=models.ImageField(null=True, upload_to='facilities/'),
        ),
        migrations.AlterField(
            model_name='featureshighlights',
            name='feature_image',
            field=models.ImageField(null=True, upload_to='features/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.ImageField(null=True, upload_to='news/'),
        ),
    ]
