# Generated by Django 5.0.3 on 2024-04-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_activities_activity_image_clubs_club_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureshighlights',
            name='feature_description',
        ),
        migrations.RemoveField(
            model_name='featureshighlights',
            name='feature_name',
        ),
        migrations.AlterField(
            model_name='activities',
            name='activity_image',
            field=models.ImageField(default=1, upload_to='activities/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clubs',
            name='club_image',
            field=models.ImageField(default=1, upload_to='clubs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facilities',
            name='facility_image',
            field=models.ImageField(upload_to='facilities/'),
        ),
        migrations.AlterField(
            model_name='featureshighlights',
            name='feature_image',
            field=models.ImageField(upload_to='features/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.ImageField(upload_to='news/'),
        ),
    ]
