# Generated by Django 5.0.3 on 2024-04-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_featureshighlights_feature_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programsoffered',
            name='accreditation',
        ),
    ]
