# Generated by Django 5.0.3 on 2024-04-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='contact_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
