# Generated by Django 5.0.3 on 2024-04-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_representative_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='school_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='representative',
            name='email_address',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
