# Generated by Django 5.0.3 on 2024-04-20 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_representative_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='representative',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.schools'),
        ),
    ]
