# Generated by Django 5.0.3 on 2024-04-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_representative_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved')], default='Not Approved', max_length=50, null=True),
        ),
    ]
