# Generated by Django 5.0.3 on 2024-04-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_representative_contact_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.AddField(
            model_name='representative',
            name='contact_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='representative',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
