# Generated by Django 5.0.3 on 2024-04-30 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_customuser_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.customuser'),
            preserve_default=False,
        ),
    ]
