# Generated by Django 5.0.3 on 2024-04-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_representative_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representative',
            name='user',
        ),
    ]
