# Generated by Django 5.0.3 on 2024-05-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_representative_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programsoffered',
            old_name='tuition_fee',
            new_name='tuition_fee_start_range',
        ),
        migrations.AddField(
            model_name='programsoffered',
            name='tuition_fee_end_range',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
