# Generated by Django 5.0.3 on 2024-05-02 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_tuition_fee_programsoffered_tuition_fee_start_range_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='process_guide',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='admission_fee',
            new_name='fee',
        ),
        migrations.RenameField(
            model_name='admission',
            old_name='requirements',
            new_name='name',
        ),
    ]
